#!/bin/bash

#idk screenshot for bg
grim /tmp/screenlock.png

# Colors
bg=$(magick /tmp/screenlock.png -resize 1x1 txt:- | grep -oE '#[A-Fa-f0-9]{6}')
bgl='313244'
fg='d9e0ee'
red='f38ba8'
green='a6e3a1'
yellow='f9e2af'
blue='89b4fa'
magenta='cba6f7'
cyan='89dceb'
alpha='00000000'

# CMD
swaylock -f \
  \
  --ignore-empty-password \
  --show-failed-attempts \
  --hide-keyboard-layout \
  --indicator-caps-lock \
  \
  --color "${bg}FF" \
  \
  --font 'Noto Sans' --font-size 30 \
  \
  --key-hl-color ${green} \
  --caps-lock-key-hl-color ${blue} \
  --bs-hl-color ${red} \
  --caps-lock-bs-hl-color ${red} \
  \
  --indicator-radius 120 \
  --indicator-thickness 10 \
  \
  --inside-color ${alpha} \
  --inside-clear-color ${alpha} \
  --inside-caps-lock-color ${alpha} \
  --inside-ver-color ${blue} \
  --inside-wrong-color ${red} \
  \
  --layout-bg-color "${bg}FF" \
  --layout-border-color ${cyan} \
  --layout-text-color ${bg} \
  \
  --line-color ${bg} \
  --line-clear-color ${red} \
  --line-caps-lock-color ${bg} \
  --line-ver-color ${bg} \
  --line-wrong-color ${bg} \
  \
  --ring-color ${cyan} \
  --ring-clear-color ${bg} \
  --ring-caps-lock-color ${magenta} \
  --ring-ver-color ${blue} \
  --ring-wrong-color ${red} \
  \
  --separator-color ${bg} \
  \
  --text-color ${fg} \
  --text-clear-color ${fg} \
  --text-caps-lock-color ${fg} \
  --text-ver-color ${bg} \
  --text-wrong-color ${bg} \
  --indicator-caps-lock # General` \
# Appearance - change CC to your desired transparency` \
#--image ${IMAGE} --scaling fill` \
# Backspace Key` \
# Indicator` \
# Inside Circle Colors` \
# Layout Colors` \
# Line Colors` \
# Ring Colors` \
# Separator Color` \
# Text Colors` \
