#!/usr/bin/env bash

iDIR="$HOME/.config/hypr/mako/icons"

# Get brightness
get_backlight() {
  LIGHT=$(printf "%d\n" $(brightnessctl g))

  # Define the minimum and maximum values
  min_brightness=9600
  max_brightness=96000

  # Calculate the percentage based on the formula
  # We map the range [min_brightness, max_brightness] to [10%, 1000%]
  percentage=$(awk -v current="$LIGHT" -v min="$min_brightness" -v max="$max_brightness" \ 'BEGIN { print int(((current - min) * 90) / (max - min) + 10) }')

  echo "${percentage}%"
}

# Get icons
get_icon() {
  backlight="$(brightnessctl g)"
  current="${backlight}"
  if [[ ("$current" -ge "0") && ("$current" -le "9600") ]]; then
    icon="$iDIR/brightness-20.png"
  elif [[ ("$current" -ge "9600") && ("$current" -le "38400") ]]; then
    icon="$iDIR/brightness-40.png"
  elif [[ ("$current" -ge "38400") && ("$current" -le "57600") ]]; then
    icon="$iDIR/brightness-60.png"
  elif [[ ("$current" -ge "57600") && ("$current" -le "76800") ]]; then
    icon="$iDIR/brightness-80.png"
  elif [[ ("$current" -ge "76800") && ("$current" -le "96000") ]]; then
    icon="$iDIR/brightness-100.png"
  fi
}

# Notify
notify_user() {
  notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$icon" "Brightness : $(get_backlight)"
}

# Increase brightness
inc_backlight() {
  brightnessctl s +5% && get_icon && notify_user
}

# Decrease brightness
dec_backlight() {
  brightnessctl s 5%- && get_icon && notify_user
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
  get_backlight
elif [[ "$1" == "--inc" ]]; then
  inc_backlight
elif [[ "$1" == "--dec" ]]; then
  dec_backlight
else
  get_backlight
fi
